version: "3"

services:
  mysqldb:
    image: mysql:latest
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    volumes:
      - /var/lib/mysql

  app:
    image: wiem441/achatwiem
    container_name: springboot-app
    restart: on-failure
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - 8089:8089
    depends_on:
      - mysqldb
