version: "3"

services:
  mysqldb:
    container_name: mysqldb
    image: mysql:8
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - /home/vagrant/mysqldata:/var/lib/mysql

  spring_app:
    image: wiem441/tpachat1
    container_name: achatproject
    restart: on-failure
    ports:
      - 9090:9090
    depends_on:
      - mysqldb