version: "2.2"
services:
  mysqldb:
    image: mysql/mysql-server:8.0
    restart: unless-stopped
    env_file: ./.env
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=tpachato
    volumes:
      - achatdb:/var/lib/mysql

  operateur_app:
    build: ./
    restart: on-failure
    environment:
      SPRING_APPLICATION_JSON: '{
              "spring.datasource.url"  : "jdbc:mysql://mysqldb:3306/tpachato?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&allowPublicKeyRetrieval=true",
              "spring.datasource.username" : "root",
              "spring.datasource.password" : "root",
              "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
              "spring.jpa.hibernate.ddl-auto" : "update"
            }'

    ports:
      - 8089:8089
    depends_on:
      - mysqldb
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true

volumes:
  achatdb:
