version: "2.2"
services:
  mysqldb:
    image: mysql/mysql-server:8.0
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=tpachato
    volumes:
      - tpachato:/var/lib/mysql

  operateur_app:
    build: ./
    restart: on-failure
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/tpachato?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    ports:
      - 8089:8089
    depends_on:
      - mysqldb

volumes:
  tpachato:
