version: "3"

services:
  mysqldb:
    container_name: mysqldb
    image: mysql/mysql-server:8.0
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: tpachato
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - /var/lib/mysql

  spring_app:
    image: wiem441/tpachat1
    container_name: achatspring
    restart: on-failure
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/tpachato?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    ports:
      - 8089:8089
    depends_on:
      - mysqldb
